version: "3"
services:
  php-fpm:
    build:
      context: .
      dockerfile: ./Dockerfile
    volumes:
    - ./:/var/www/html
  nginx:
    image: nginx:1.9-alpine
    depends_on:
      - php-fpm
    healthcheck:
      test: ["CMD", "curl", "http://nginx/health"]
      interval: 1s
      timeout: 5s
      retries: 3
    volumes:
    - ./nginx-fpm.conf:/etc/nginx/conf.d/default.conf
    - ./public:/usr/share/nginx/html/public
    ports:
      - 8000:80
      - 8443:443
